/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BackupListerExpansion allows custom methods to be added to
// BackupLister.
type BackupListerExpansion interface{}

// BackupNamespaceListerExpansion allows custom methods to be added to
// BackupNamespaceLister.
type BackupNamespaceListerExpansion interface{}

// DbListerExpansion allows custom methods to be added to
// DbLister.
type DbListerExpansion interface{}

// DbNamespaceListerExpansion allows custom methods to be added to
// DbNamespaceLister.
type DbNamespaceListerExpansion interface{}

// DbBackupListerExpansion allows custom methods to be added to
// DbBackupLister.
type DbBackupListerExpansion interface{}

// DbBackupNamespaceListerExpansion allows custom methods to be added to
// DbBackupNamespaceLister.
type DbBackupNamespaceListerExpansion interface{}

// DbRestoreListerExpansion allows custom methods to be added to
// DbRestoreLister.
type DbRestoreListerExpansion interface{}

// DbRestoreNamespaceListerExpansion allows custom methods to be added to
// DbRestoreNamespaceLister.
type DbRestoreNamespaceListerExpansion interface{}

// DbServiceListerExpansion allows custom methods to be added to
// DbServiceLister.
type DbServiceListerExpansion interface{}

// DbServiceNamespaceListerExpansion allows custom methods to be added to
// DbServiceNamespaceLister.
type DbServiceNamespaceListerExpansion interface{}

// GlobalDBListerExpansion allows custom methods to be added to
// GlobalDBLister.
type GlobalDBListerExpansion interface{}

// GlobalDBNamespaceListerExpansion allows custom methods to be added to
// GlobalDBNamespaceLister.
type GlobalDBNamespaceListerExpansion interface{}

// RestoreListerExpansion allows custom methods to be added to
// RestoreLister.
type RestoreListerExpansion interface{}

// RestoreNamespaceListerExpansion allows custom methods to be added to
// RestoreNamespaceLister.
type RestoreNamespaceListerExpansion interface{}
