/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "gitlab.zcorp.cc/pangu/cne-api/apis/qucheng/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGlobalDBs implements GlobalDBInterface
type FakeGlobalDBs struct {
	Fake *FakeQuchengV1beta1
	ns   string
}

var globaldbsResource = schema.GroupVersionResource{Group: "qucheng", Version: "v1beta1", Resource: "globaldbs"}

var globaldbsKind = schema.GroupVersionKind{Group: "qucheng", Version: "v1beta1", Kind: "GlobalDB"}

// Get takes name of the globalDB, and returns the corresponding globalDB object, and an error if there is any.
func (c *FakeGlobalDBs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GlobalDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(globaldbsResource, c.ns, name), &v1beta1.GlobalDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GlobalDB), err
}

// List takes label and field selectors, and returns the list of GlobalDBs that match those selectors.
func (c *FakeGlobalDBs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GlobalDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(globaldbsResource, globaldbsKind, c.ns, opts), &v1beta1.GlobalDBList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GlobalDBList{ListMeta: obj.(*v1beta1.GlobalDBList).ListMeta}
	for _, item := range obj.(*v1beta1.GlobalDBList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested globalDBs.
func (c *FakeGlobalDBs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(globaldbsResource, c.ns, opts))

}

// Create takes the representation of a globalDB and creates it.  Returns the server's representation of the globalDB, and an error, if there is any.
func (c *FakeGlobalDBs) Create(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.CreateOptions) (result *v1beta1.GlobalDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(globaldbsResource, c.ns, globalDB), &v1beta1.GlobalDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GlobalDB), err
}

// Update takes the representation of a globalDB and updates it. Returns the server's representation of the globalDB, and an error, if there is any.
func (c *FakeGlobalDBs) Update(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.UpdateOptions) (result *v1beta1.GlobalDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(globaldbsResource, c.ns, globalDB), &v1beta1.GlobalDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GlobalDB), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGlobalDBs) UpdateStatus(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.UpdateOptions) (*v1beta1.GlobalDB, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(globaldbsResource, "status", c.ns, globalDB), &v1beta1.GlobalDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GlobalDB), err
}

// Delete takes name of the globalDB and deletes it. Returns an error if one occurs.
func (c *FakeGlobalDBs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(globaldbsResource, c.ns, name, opts), &v1beta1.GlobalDB{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGlobalDBs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(globaldbsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GlobalDBList{})
	return err
}

// Patch applies the patch and returns the patched globalDB.
func (c *FakeGlobalDBs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GlobalDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(globaldbsResource, c.ns, name, pt, data, subresources...), &v1beta1.GlobalDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GlobalDB), err
}
