/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "gitlab.zcorp.cc/pangu/cne-api/apis/qucheng/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDbServices implements DbServiceInterface
type FakeDbServices struct {
	Fake *FakeQuchengV1beta1
	ns   string
}

var dbservicesResource = schema.GroupVersionResource{Group: "qucheng", Version: "v1beta1", Resource: "dbservices"}

var dbservicesKind = schema.GroupVersionKind{Group: "qucheng", Version: "v1beta1", Kind: "DbService"}

// Get takes name of the dbService, and returns the corresponding dbService object, and an error if there is any.
func (c *FakeDbServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.DbService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dbservicesResource, c.ns, name), &v1beta1.DbService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DbService), err
}

// List takes label and field selectors, and returns the list of DbServices that match those selectors.
func (c *FakeDbServices) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.DbServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dbservicesResource, dbservicesKind, c.ns, opts), &v1beta1.DbServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.DbServiceList{ListMeta: obj.(*v1beta1.DbServiceList).ListMeta}
	for _, item := range obj.(*v1beta1.DbServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dbServices.
func (c *FakeDbServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dbservicesResource, c.ns, opts))

}

// Create takes the representation of a dbService and creates it.  Returns the server's representation of the dbService, and an error, if there is any.
func (c *FakeDbServices) Create(ctx context.Context, dbService *v1beta1.DbService, opts v1.CreateOptions) (result *v1beta1.DbService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dbservicesResource, c.ns, dbService), &v1beta1.DbService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DbService), err
}

// Update takes the representation of a dbService and updates it. Returns the server's representation of the dbService, and an error, if there is any.
func (c *FakeDbServices) Update(ctx context.Context, dbService *v1beta1.DbService, opts v1.UpdateOptions) (result *v1beta1.DbService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dbservicesResource, c.ns, dbService), &v1beta1.DbService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DbService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDbServices) UpdateStatus(ctx context.Context, dbService *v1beta1.DbService, opts v1.UpdateOptions) (*v1beta1.DbService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dbservicesResource, "status", c.ns, dbService), &v1beta1.DbService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DbService), err
}

// Delete takes name of the dbService and deletes it. Returns an error if one occurs.
func (c *FakeDbServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dbservicesResource, c.ns, name, opts), &v1beta1.DbService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDbServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dbservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.DbServiceList{})
	return err
}

// Patch applies the patch and returns the patched dbService.
func (c *FakeDbServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DbService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dbservicesResource, c.ns, name, pt, data, subresources...), &v1beta1.DbService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DbService), err
}
