#!/bin/sh
set -e
set -u

n=0
max=2
until [ $n -gt $max ]; do
    set +e
    (
      apk --no-cache add "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "apk failed, retrying"
    n=$(($n + 1))
done
rm -rf /var/cache/apk/*