/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "gitlab.zcorp.cc/pangu/cne-api/apis/qucheng/v1beta1"
	scheme "gitlab.zcorp.cc/pangu/cne-api/pkg/client/cne/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DbRestoresGetter has a method to return a DbRestoreInterface.
// A group's client should implement this interface.
type DbRestoresGetter interface {
	DbRestores(namespace string) DbRestoreInterface
}

// DbRestoreInterface has methods to work with DbRestore resources.
type DbRestoreInterface interface {
	Create(ctx context.Context, dbRestore *v1beta1.DbRestore, opts v1.CreateOptions) (*v1beta1.DbRestore, error)
	Update(ctx context.Context, dbRestore *v1beta1.DbRestore, opts v1.UpdateOptions) (*v1beta1.DbRestore, error)
	UpdateStatus(ctx context.Context, dbRestore *v1beta1.DbRestore, opts v1.UpdateOptions) (*v1beta1.DbRestore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.DbRestore, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.DbRestoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DbRestore, err error)
	DbRestoreExpansion
}

// dbRestores implements DbRestoreInterface
type dbRestores struct {
	client rest.Interface
	ns     string
}

// newDbRestores returns a DbRestores
func newDbRestores(c *QuchengV1beta1Client, namespace string) *dbRestores {
	return &dbRestores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dbRestore, and returns the corresponding dbRestore object, and an error if there is any.
func (c *dbRestores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.DbRestore, err error) {
	result = &v1beta1.DbRestore{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dbrestores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DbRestores that match those selectors.
func (c *dbRestores) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.DbRestoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.DbRestoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dbrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dbRestores.
func (c *dbRestores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dbrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dbRestore and creates it.  Returns the server's representation of the dbRestore, and an error, if there is any.
func (c *dbRestores) Create(ctx context.Context, dbRestore *v1beta1.DbRestore, opts v1.CreateOptions) (result *v1beta1.DbRestore, err error) {
	result = &v1beta1.DbRestore{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dbrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dbRestore).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dbRestore and updates it. Returns the server's representation of the dbRestore, and an error, if there is any.
func (c *dbRestores) Update(ctx context.Context, dbRestore *v1beta1.DbRestore, opts v1.UpdateOptions) (result *v1beta1.DbRestore, err error) {
	result = &v1beta1.DbRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dbrestores").
		Name(dbRestore.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dbRestore).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dbRestores) UpdateStatus(ctx context.Context, dbRestore *v1beta1.DbRestore, opts v1.UpdateOptions) (result *v1beta1.DbRestore, err error) {
	result = &v1beta1.DbRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dbrestores").
		Name(dbRestore.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dbRestore).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dbRestore and deletes it. Returns an error if one occurs.
func (c *dbRestores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dbrestores").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dbRestores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dbrestores").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dbRestore.
func (c *dbRestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DbRestore, err error) {
	result = &v1beta1.DbRestore{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dbrestores").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
