/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "gitlab.zcorp.cc/pangu/cne-api/apis/qucheng/v1beta1"
	scheme "gitlab.zcorp.cc/pangu/cne-api/pkg/client/cne/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalDBsGetter has a method to return a GlobalDBInterface.
// A group's client should implement this interface.
type GlobalDBsGetter interface {
	GlobalDBs(namespace string) GlobalDBInterface
}

// GlobalDBInterface has methods to work with GlobalDB resources.
type GlobalDBInterface interface {
	Create(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.CreateOptions) (*v1beta1.GlobalDB, error)
	Update(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.UpdateOptions) (*v1beta1.GlobalDB, error)
	UpdateStatus(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.UpdateOptions) (*v1beta1.GlobalDB, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.GlobalDB, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.GlobalDBList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GlobalDB, err error)
	GlobalDBExpansion
}

// globalDBs implements GlobalDBInterface
type globalDBs struct {
	client rest.Interface
	ns     string
}

// newGlobalDBs returns a GlobalDBs
func newGlobalDBs(c *QuchengV1beta1Client, namespace string) *globalDBs {
	return &globalDBs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the globalDB, and returns the corresponding globalDB object, and an error if there is any.
func (c *globalDBs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GlobalDB, err error) {
	result = &v1beta1.GlobalDB{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globaldbs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalDBs that match those selectors.
func (c *globalDBs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GlobalDBList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.GlobalDBList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globaldbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalDBs.
func (c *globalDBs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("globaldbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a globalDB and creates it.  Returns the server's representation of the globalDB, and an error, if there is any.
func (c *globalDBs) Create(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.CreateOptions) (result *v1beta1.GlobalDB, err error) {
	result = &v1beta1.GlobalDB{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("globaldbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalDB).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a globalDB and updates it. Returns the server's representation of the globalDB, and an error, if there is any.
func (c *globalDBs) Update(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.UpdateOptions) (result *v1beta1.GlobalDB, err error) {
	result = &v1beta1.GlobalDB{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globaldbs").
		Name(globalDB.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalDB).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *globalDBs) UpdateStatus(ctx context.Context, globalDB *v1beta1.GlobalDB, opts v1.UpdateOptions) (result *v1beta1.GlobalDB, err error) {
	result = &v1beta1.GlobalDB{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globaldbs").
		Name(globalDB.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalDB).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the globalDB and deletes it. Returns an error if one occurs.
func (c *globalDBs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globaldbs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalDBs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globaldbs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched globalDB.
func (c *globalDBs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GlobalDB, err error) {
	result = &v1beta1.GlobalDB{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("globaldbs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
